### ISSUE TITLE
Failed to activate the ginkgo-and-gomega-snippets package

### ISSUE THREAD

**Issue by voelzmo** [evankline/ginkgo-and-gomega-snippets#3]
[Enter steps to reproduce below:]

1. Install ginkgo-and-gomega-snippets 
2. restart atom
3. Hit `ctrl+option+O`

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [ginkgo-and-gomega-snippets](https://github.com/evankline/ginkgo-and-gomega-snippets) package, v0.1.5

### Stack Trace

Failed to activate the ginkgo-and-gomega-snippets package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/d058546/workspace/dotfiles/atom/packages/ginkgo-and-gomega-snippets/lib/ginkgo-and-gomega-snippets-view.coffee:4:199)
    at /Users/d058546/workspace/dotfiles/atom/packages/ginkgo-and-gomega-snippets/lib/ginkgo-and-gomega-snippets-view.coffee:9:5
    at Object.<anonymous> (/Users/d058546/workspace/dotfiles/atom/packages/ginkgo-and-gomega-snippets/lib/ginkgo-and-gomega-snippets-view.coffee:52:5)
    at Object.<anonymous> (/Users/d058546/workspace/dotfiles/atom/packages/ginkgo-and-gomega-snippets/lib/ginkgo-and-gomega-snippets-view.coffee:54:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```

### Commands

```
     -0:00.5.0 ginkgo-and-gomega-snippets:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
autocomplete-paths, v1.0.2
ginkgo-and-gomega-snippets, v0.1.5
go-plus, v3.5.1
highlight-selected, v0.10.1
language-docker, v1.1.3
language-nginx, v0.6.1
language-rspec, v0.3.0
linter, v1.9.0
linter-clojure, v1.0.0
linter-csslint, v1.1.0
linter-erb, v0.1.1
linter-js-yaml, v1.1.2
linter-jshint, v1.2.1
linter-rubocop, v0.4.4
linter-shellcheck, v1.0.2
linter-tidy, v1.0.1
minimap, v4.15.0
minimap-highlight-selected, v4.3.1
pretty-json, v0.4.1
rspec-snippets, v0.4.0

# Dev
No dev packages
```

**Comment by voelzmo** [comment]
Actually a duplicate of https://github.com/evankline/ginkgo-and-gomega-snippets/issues/2
